services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      CON_STRING: postgresql://user:userpass@postgres:5432/week2_2_xsolla
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: week2_2_xsolla
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d week2_2_xsolla"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: