apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - api.yaml
  - api-config.yaml

configMapGenerator:
  - name: postgres-migrations
    files:
      - init.sql=postgres-init.sql